import type { EntityNode, RelationEdge, InstanceDataset } from '../types'

function toUpperSnake(name: string): string {
  return name.replace(/([A-Z])/g, '_$1').toUpperCase().replace(/^_/, '')
}

function cypherValue(v: unknown): string {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return String(v)
}

/** Safely reference a Neo4j property — names with spaces/special chars need backtick quoting */
function cypherProp(name: string, alias = 'n'): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? `${alias}.${name}` : `${alias}.\`${name}\``
}

export function generateCypher(
  datasets: InstanceDataset[],
  nodes: EntityNode[],
  edges: RelationEdge[],
): string {
  const lines: string[] = []
  const now = new Date().toISOString()
  const modelId = datasets[0]?.modelId ?? ''

  lines.push(`// Generated by Ontology Studio — ${now}`)
  lines.push(`// Model: ${modelId}`)
  lines.push(`//`)
  lines.push(`// ⚠️  注意：此文件为面向 Neo4j Browser 的直接执行格式（使用业务标签如 :Person, :Trip）`)
  lines.push(`// 若需通过本系统 UI 重新导入，请使用"导出 Excel"功能，逐实体类型上传 CSV。`)
  lines.push('')

  // Build entity MERGE statements
  for (const ds of datasets) {
    const entityNode = nodes.find((n) => n.id === ds.entityNodeId)
    if (!entityNode) continue
    const label = entityNode.data.name
    const props = entityNode.data.properties
    const idProp = props.find((p) => p.unique) ?? props.find((p) => p.name === 'id') ?? props.find((p) => p.required)

    lines.push(`// ── ${entityNode.data.label || label} (${ds.records.length} 条) ──`)

    for (const record of ds.records) {
      if (!idProp || record.data[idProp.name] == null) continue
      const mergeKey = `${cypherProp(idProp.name)}: ${cypherValue(record.data[idProp.name])}`
      const setProps = Object.entries(record.data)
        .filter(([k, v]) => k !== idProp.name && v !== null && v !== undefined && v !== '')
        .map(([k, v]) => `${cypherProp(k)} = ${cypherValue(v)}`)
      lines.push(`MERGE (n:${label} {${mergeKey}})`)
      if (setProps.length > 0) lines.push(`  SET ${setProps.join(', ')}`)
    }
    lines.push('')
  }

  // Build relationship MERGE statements using sourceKey/targetKey FK fields
  for (const edge of edges) {
    const sourceKey = edge.data?.sourceKey
    const targetKey = edge.data?.targetKey
    if (!sourceKey || !targetKey) continue

    const sourceDs = datasets.find((d) => d.entityNodeId === edge.source)
    const targetDs = datasets.find((d) => d.entityNodeId === edge.target)
    if (!sourceDs || !targetDs) continue

    const sourceNode = nodes.find((n) => n.id === edge.source)
    const targetNode = nodes.find((n) => n.id === edge.target)
    if (!sourceNode || !targetNode) continue

    const relType = toUpperSnake(edge.data?.name ?? 'RELATED_TO')
    const srcLabel = sourceNode.data.name
    const tgtLabel = targetNode.data.name

    // Build lookup map: targetKey value → target record merge key
    const tgtIdProp = targetNode.data.properties.find((p) => p.unique)
      ?? targetNode.data.properties.find((p) => p.name === 'id')
      ?? targetNode.data.properties.find((p) => p.required)
    if (!tgtIdProp) continue

    const tgtMap = new Map<unknown, unknown>()
    for (const rec of targetDs.records) {
      const fkVal = rec.data[targetKey]
      const idVal = rec.data[tgtIdProp.name]
      if (fkVal != null && idVal != null) tgtMap.set(String(fkVal), idVal)
    }

    const srcIdProp = sourceNode.data.properties.find((p) => p.unique)
      ?? sourceNode.data.properties.find((p) => p.name === 'id')
      ?? sourceNode.data.properties.find((p) => p.required)
    if (!srcIdProp) continue

    const relLines: string[] = []
    for (const srcRec of sourceDs.records) {
      const fkVal = srcRec.data[sourceKey]
      const tgtId = fkVal != null ? tgtMap.get(String(fkVal)) : undefined
      const srcId = srcRec.data[srcIdProp.name]
      if (tgtId == null || srcId == null) continue
      relLines.push(`MATCH (a:${srcLabel} {${cypherProp(srcIdProp.name, 'a')}: ${cypherValue(srcId)}}), ` +
        `(b:${tgtLabel} {${cypherProp(tgtIdProp.name, 'b')}: ${cypherValue(tgtId)}})`)
      relLines.push(`MERGE (a)-[:${relType}]->(b)`)
    }

    if (relLines.length > 0) {
      lines.push(`// ── ${srcLabel} -[:${relType}]-> ${tgtLabel} (via ${sourceKey}→${targetKey}) ──`)
      lines.push(...relLines)
      lines.push('')
    }
  }

  return lines.join('\n')
}

export function downloadCypher(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

/**
 * Export all instance datasets as a multi-sheet Excel workbook.
 * Each sheet = one entity type, headers = property English names.
 * This format is directly re-importable via the system's CSV import UI.
 */
export async function exportTwinAsExcel(
  datasets: InstanceDataset[],
  nodes: EntityNode[],
  twinName: string,
): Promise<void> {
  const XLSX = await import('xlsx')
  const wb = XLSX.utils.book_new()

  // Sheet 0: import instructions
  const readmeRows: unknown[][] = [
    ['导入说明'],
    [''],
    ['本文件由 Ontology Studio 导出，每个 Sheet 对应一种实体类型。'],
    ['导入步骤：在业务孪生的"导入数据"标签页，按下方顺序逐个实体上传对应 Sheet（另存为 CSV）。'],
    ['先导入父实体，再导入子实体，确保外键字段能正确连边。'],
    [''],
    ['序号', '实体中文名', '实体英文名', '记录数'],
  ]
  let idx = 1
  for (const ds of datasets) {
    const node = nodes.find((n) => n.id === ds.entityNodeId)
    if (!node || ds.records.length === 0) continue
    readmeRows.push([idx++, node.data.label || node.data.name, node.data.name, ds.records.length])
  }
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(readmeRows), '导入说明')

  // One sheet per entity type
  for (const ds of datasets) {
    const node = nodes.find((n) => n.id === ds.entityNodeId)
    if (!node || ds.records.length === 0) continue

    const props = node.data.properties
    if (props.length === 0) continue

    const headers = props.map((p) => p.name)
    const dataRows = ds.records.map((r) =>
      headers.map((h) => {
        const v = r.data[h]
        return v === null || v === undefined ? '' : v
      })
    )

    const ws = XLSX.utils.aoa_to_sheet([headers, ...dataRows])
    // Excel sheet names: max 31 chars, no special chars
    const rawName = (node.data.label || node.data.name).replace(/[:/\\?*[\]]/g, '_')
    const sheetName = rawName.slice(0, 31)
    XLSX.utils.book_append_sheet(wb, ws, sheetName)
  }

  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
  const blob = new Blob([out], { type: 'application/octet-stream' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `twin-${twinName.replace(/[^A-Za-z0-9一-龥]/g, '_')}-${new Date().toISOString().slice(0, 10)}.xlsx`
  a.click()
  URL.revokeObjectURL(url)
}
