import type { EntityNode, RelationEdge, InstanceDataset } from '../types'

function toUpperSnake(name: string): string {
  return name.replace(/([A-Z])/g, '_$1').toUpperCase().replace(/^_/, '')
}

function cypherValue(v: unknown): string {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return String(v)
}

export function generateCypher(
  datasets: InstanceDataset[],
  nodes: EntityNode[],
  edges: RelationEdge[],
): string {
  const lines: string[] = []
  const now = new Date().toISOString()
  const modelId = datasets[0]?.modelId ?? ''

  lines.push(`// Generated by Ontology Studio — ${now}`)
  lines.push(`// Model: ${modelId}`)
  lines.push('')

  // Build entity MERGE statements
  for (const ds of datasets) {
    const entityNode = nodes.find((n) => n.id === ds.entityNodeId)
    if (!entityNode) continue
    const label = entityNode.data.name
    const props = entityNode.data.properties
    const idProp = props.find((p) => p.name === 'id') ?? props.find((p) => p.required)

    lines.push(`// ── ${entityNode.data.label || label} (${ds.records.length} 条) ──`)

    for (const record of ds.records) {
      if (!idProp || record.data[idProp.name] == null) continue
      const mergeKey = `${idProp.name}: ${cypherValue(record.data[idProp.name])}`
      const setProps = Object.entries(record.data)
        .filter(([k, v]) => k !== idProp.name && v !== null && v !== undefined)
        .map(([k, v]) => `n.${k} = ${cypherValue(v)}`)
      lines.push(`MERGE (n:${label} {${mergeKey}})`)
      if (setProps.length > 0) lines.push(`  SET ${setProps.join(', ')}`)
    }
    lines.push('')
  }

  // Build relationship MERGE statements
  for (const edge of edges) {
    const sourceDs = datasets.find((d) => d.entityNodeId === edge.source)
    const targetDs = datasets.find((d) => d.entityNodeId === edge.target)
    if (!sourceDs || !targetDs) continue

    const sourceNode = nodes.find((n) => n.id === edge.source)
    const targetNode = nodes.find((n) => n.id === edge.target)
    if (!sourceNode || !targetNode) continue

    const relType = toUpperSnake(edge.data?.name ?? 'RELATED_TO')
    const srcLabel = sourceNode.data.name
    const tgtLabel = targetNode.data.name
    const srcIdProp = sourceNode.data.properties.find((p) => p.name === 'id') ?? sourceNode.data.properties.find((p) => p.required)
    const tgtIdProp = targetNode.data.properties.find((p) => p.name === 'id') ?? targetNode.data.properties.find((p) => p.required)
    if (!srcIdProp || !tgtIdProp) continue

    lines.push(`// ── ${srcLabel} -[:${relType}]-> ${tgtLabel} ──`)
    for (const srcRec of sourceDs.records) {
      const srcId = srcRec.data[srcIdProp.name]
      if (srcId == null) continue
      for (const tgtRec of targetDs.records) {
        const tgtId = tgtRec.data[tgtIdProp.name]
        if (tgtId == null) continue
        // Only create edge if source record references target id
        const refVal = srcRec.data[edge.data?.name ?? '']
        if (refVal !== tgtId) continue
        lines.push(`MATCH (a:${srcLabel} {${srcIdProp.name}: ${cypherValue(srcId)}}), (b:${tgtLabel} {${tgtIdProp.name}: ${cypherValue(tgtId)}})`)
        lines.push(`MERGE (a)-[:${relType}]->(b)`)
      }
    }
    lines.push('')
  }

  return lines.join('\n')
}

export function downloadCypher(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}
